[package]
name = "askama-bug"
version = "0.1.0"
authors = ["Bernhard Schuster <bernhard@ahoi.io>"]
edition = "2018"
build = "build.rs"

[dependencies]
askama = "0.7"


[build-dependencies]
askama = "0.7"